import { BeltStatus, DamageDetection, MaintenancePrediction, ThermalReading, Alert, DashboardStats, AnalysisRecord } from "./types";

// ===== MOCK DATA =====

export const mockBelts: BeltStatus[] = [
  {
    id: "BLT-001",
    name: "Main Haulage Belt - Sector A",
    status: "operational",
    speed: 4.2,
    tension: 85,
    temperature: 38,
    load: 2400,
    uptime: 98.5,
    lastInspection: "2026-08-25",
    damageRisk: 12,
  },
  {
    id: "BLT-002",
    name: "Crusher Feed Belt - Zone B",
    status: "warning",
    speed: 3.8,
    tension: 92,
    temperature: 52,
    load: 1800,
    uptime: 94.2,
    lastInspection: "2026-08-24",
    damageRisk: 45,
  },
  {
    id: "BLT-003",
    name: "Stockpile Reclaimer - Zone C",
    status: "critical",
    speed: 2.1,
    tension: 110,
    temperature: 68,
    load: 1200,
    uptime: 82.1,
    lastInspection: "2026-08-20",
    damageRisk: 78,
  },
  {
    id: "BLT-004",
    name: "Overland Conveyor - Route 1",
    status: "operational",
    speed: 5.0,
    tension: 78,
    temperature: 35,
    load: 3200,
    uptime: 99.1,
    lastInspection: "2026-08-26",
    damageRisk: 8,
  },
  {
    id: "BLT-005",
    name: "Port Loading Belt - Dock A",
    status: "offline",
    speed: 0,
    tension: 0,
    temperature: 28,
    load: 0,
    uptime: 91.7,
    lastInspection: "2026-08-18",
    damageRisk: 0,
  },
  {
    id: "BLT-006",
    name: "Waste Rock Conveyor - Sector D",
    status: "operational",
    speed: 3.5,
    tension: 72,
    temperature: 41,
    load: 1600,
    uptime: 97.3,
    lastInspection: "2026-08-26",
    damageRisk: 15,
  },
  {
    id: "BLT-007",
    name: "Primary Crusher Discharge",
    status: "warning",
    speed: 4.0,
    tension: 88,
    temperature: 55,
    load: 2100,
    uptime: 93.8,
    lastInspection: "2026-08-23",
    damageRisk: 52,
  },
  {
    id: "BLT-008",
    name: "Beneficiation Plant Feed",
    status: "operational",
    speed: 4.5,
    tension: 80,
    temperature: 36,
    load: 2800,
    uptime: 98.9,
    lastInspection: "2026-08-25",
    damageRisk: 10,
  },
];

export const mockDetections: DamageDetection[] = [
  {
    id: "DET-001",
    beltId: "BLT-003",
    type: "joint_rupture",
    severity: "critical",
    confidence: 94.2,
    location: "Joint Section 12 - 340m mark",
    timestamp: "2026-08-27T08:15:00Z",
    imageUrl: "/detections/joint-rupture-001.jpg",
    status: "detected",
  },
  {
    id: "DET-002",
    beltId: "BLT-002",
    type: "tear",
    severity: "high",
    confidence: 88.7,
    location: "Belt Span 7 - 180m mark",
    timestamp: "2026-08-27T06:42:00Z",
    imageUrl: "/detections/tear-002.jpg",
    status: "acknowledged",
  },
  {
    id: "DET-003",
    beltId: "BLT-007",
    type: "abrasion",
    severity: "medium",
    confidence: 76.5,
    location: "Loading Zone - Transfer Point B",
    timestamp: "2026-08-26T14:20:00Z",
    imageUrl: "/detections/abrasion-003.jpg",
    status: "detected",
  },
  {
    id: "DET-004",
    beltId: "BLT-001",
    type: "edge_damage",
    severity: "low",
    confidence: 82.1,
    location: "Return Side - Idler Station 5",
    timestamp: "2026-08-26T09:10:00Z",
    imageUrl: "/detections/edge-004.jpg",
    status: "repaired",
  },
  {
    id: "DET-005",
    beltId: "BLT-003",
    type: "splice_failure",
    severity: "high",
    confidence: 91.3,
    location: "Splice Point 4 - 520m mark",
    timestamp: "2026-08-25T16:55:00Z",
    imageUrl: "/detections/splice-005.jpg",
    status: "detected",
  },
  {
    id: "DET-006",
    beltId: "BLT-002",
    type: "tear",
    severity: "medium",
    confidence: 79.8,
    location: "Impact Zone - Below Crusher",
    timestamp: "2026-08-25T11:30:00Z",
    imageUrl: "/detections/tear-006.jpg",
    status: "repaired",
  },
];

export const mockPredictions: MaintenancePrediction[] = [
  {
    id: "PRD-001",
    beltId: "BLT-003",
    component: "Belt Cover - Top Ply",
    predictedFailureDate: "2026-09-05",
    confidence: 89.4,
    remainingLife: 9,
    priority: "urgent",
    recommendation: "Immediate replacement of top ply section recommended. Risk of full rupture within 9 days.",
  },
  {
    id: "PRD-002",
    beltId: "BLT-002",
    component: "Drive Pulley Bearing",
    predictedFailureDate: "2026-09-15",
    confidence: 76.8,
    remainingLife: 19,
    priority: "high",
    recommendation: "Schedule bearing replacement during next planned shutdown. Vibration levels increasing.",
  },
  {
    id: "PRD-003",
    beltId: "BLT-007",
    component: "Impact Idlers - Zone 3",
    predictedFailureDate: "2026-09-20",
    confidence: 68.2,
    remainingLife: 24,
    priority: "medium",
    recommendation: "Replace impact idlers in Zone 3. Increased belt sag detected at loading point.",
  },
  {
    id: "PRD-004",
    beltId: "BLT-001",
    component: "Belt Splice - Joint A",
    predictedFailureDate: "2026-10-12",
    confidence: 62.1,
    remainingLife: 46,
    priority: "low",
    recommendation: "Monitor splice condition. No immediate action required. Re-scan in 2 weeks.",
  },
  {
    id: "PRD-005",
    beltId: "BLT-006",
    component: "Tail Pulley Lagging",
    predictedFailureDate: "2026-09-28",
    confidence: 71.5,
    remainingLife: 32,
    priority: "medium",
    recommendation: "Schedule lagging replacement. Early signs of wear detected through CV analysis.",
  },
];

export const mockThermalData: ThermalReading[] = [
  { id: "THR-001", beltId: "BLT-001", zone: "Drive Station", temperature: 42.3, anomalyScore: 0.12, timestamp: "2026-08-27T08:00:00Z", status: "normal" },
  { id: "THR-002", beltId: "BLT-001", zone: "Loading Point", temperature: 45.1, anomalyScore: 0.18, timestamp: "2026-08-27T08:00:00Z", status: "normal" },
  { id: "THR-003", beltId: "BLT-002", zone: "Drive Station", temperature: 62.5, anomalyScore: 0.67, timestamp: "2026-08-27T08:00:00Z", status: "elevated" },
  { id: "THR-004", beltId: "BLT-002", zone: "Bearing Housing", temperature: 71.8, anomalyScore: 0.85, timestamp: "2026-08-27T08:00:00Z", status: "critical" },
  { id: "THR-005", beltId: "BLT-003", zone: "Joint Area", temperature: 78.4, anomalyScore: 0.92, timestamp: "2026-08-27T08:00:00Z", status: "critical" },
  { id: "THR-006", beltId: "BLT-003", zone: "Splice Section", temperature: 65.2, anomalyScore: 0.73, timestamp: "2026-08-27T08:00:00Z", status: "elevated" },
  { id: "THR-007", beltId: "BLT-004", zone: "Drive Station", temperature: 38.9, anomalyScore: 0.08, timestamp: "2026-08-27T08:00:00Z", status: "normal" },
  { id: "THR-008", beltId: "BLT-006", zone: "Tail Station", temperature: 41.2, anomalyScore: 0.15, timestamp: "2026-08-27T08:00:00Z", status: "normal" },
  { id: "THR-009", beltId: "BLT-007", zone: "Crusher Discharge", temperature: 58.7, anomalyScore: 0.55, timestamp: "2026-08-27T08:00:00Z", status: "elevated" },
  { id: "THR-010", beltId: "BLT-008", zone: "Loading Zone", temperature: 39.5, anomalyScore: 0.10, timestamp: "2026-08-27T08:00:00Z", status: "normal" },
];

export const mockAlerts: Alert[] = [
  { id: "ALT-001", type: "damage", severity: "critical", message: "Joint rupture detected on BLT-003 at 340m mark. Confidence: 94.2%", timestamp: "2026-08-27T08:15:00Z", acknowledged: false },
  { id: "ALT-002", type: "thermal", severity: "warning", message: "Abnormal temperature on BLT-002 bearing housing: 71.8°C (threshold: 65°C)", timestamp: "2026-08-27T07:50:00Z", acknowledged: false },
  { id: "ALT-003", type: "maintenance", severity: "critical", message: "BLT-003 top ply predicted failure in 9 days - immediate replacement required", timestamp: "2026-08-27T07:30:00Z", acknowledged: false },
  { id: "ALT-004", type: "damage", severity: "warning", message: "Tear detected on BLT-002 at 180m mark. Confidence: 88.7%", timestamp: "2026-08-27T06:42:00Z", acknowledged: true },
  { id: "ALT-005", type: "system", severity: "info", message: "BLT-005 Port Loading Belt taken offline for scheduled maintenance", timestamp: "2026-08-27T06:00:00Z", acknowledged: true },
  { id: "ALT-006", type: "thermal", severity: "warning", message: "Elevated temperature on BLT-007 crusher discharge: 58.7°C", timestamp: "2026-08-27T05:45:00Z", acknowledged: false },
  { id: "ALT-007", type: "maintenance", severity: "info", message: "BLT-004 splice joint monitoring schedule updated - next scan: 2026-08-28", timestamp: "2026-08-26T18:00:00Z", acknowledged: true },
];

export const mockDashboardStats: DashboardStats = {
  totalBelts: 8,
  operationalBelts: 4,
  warningBelts: 2,
  criticalBelts: 1,
  activeAlerts: 5,
  avgUptime: 95.7,
  totalTonnage: 15100,
  damageDetections: 6,
  predictionsPending: 5,
};

// Chart data
export const productionChartData = [
  { month: "Mar", tonnage: 42000, target: 45000 },
  { month: "Apr", tonnage: 44500, target: 45000 },
  { month: "May", tonnage: 38000, target: 45000 },
  { month: "Jun", tonnage: 46200, target: 45000 },
  { month: "Jul", tonnage: 47800, target: 45000 },
  { month: "Aug", tonnage: 39200, target: 45000 },
];

export const damageTrendData = [
  { month: "Mar", tears: 3, abrasions: 5, jointFailures: 1, edgeDamage: 2 },
  { month: "Apr", tears: 2, abrasions: 4, jointFailures: 2, edgeDamage: 1 },
  { month: "May", tears: 5, abrasions: 6, jointFailures: 3, edgeDamage: 3 },
  { month: "Jun", tears: 1, abrasions: 3, jointFailures: 1, edgeDamage: 2 },
  { month: "Jul", tears: 2, abrasions: 4, jointFailures: 2, edgeDamage: 1 },
  { month: "Aug", tears: 4, abrasions: 5, jointFailures: 2, edgeDamage: 1 },
];

export const uptimeChartData = [
  { name: "BLT-001", uptime: 98.5, status: "operational" },
  { name: "BLT-002", uptime: 94.2, status: "warning" },
  { name: "BLT-003", uptime: 82.1, status: "critical" },
  { name: "BLT-004", uptime: 99.1, status: "operational" },
  { name: "BLT-005", uptime: 91.7, status: "offline" },
  { name: "BLT-006", uptime: 97.3, status: "operational" },
  { name: "BLT-007", uptime: 93.8, status: "warning" },
  { name: "BLT-008", uptime: 98.9, status: "operational" },
];

export const mockAnalysisData: AnalysisRecord[] = [
  // Vibration
  { id: "ANL-001", beltId: "BLT-003", category: "vibration", component: "Drive Pulley Bearing", value: 12.4, unit: "mm/s", threshold: 10, status: "critical", severity: "high", details: "Bearing vibration 24% above threshold. Axial displacement detected.", recommendation: "Schedule immediate bearing replacement. Check alignment.", timestamp: "2026-08-27T08:00:00Z" },
  { id: "ANL-002", beltId: "BLT-002", category: "vibration", component: "Tail Pulley", value: 7.8, unit: "mm/s", threshold: 10, status: "warning", severity: "medium", details: "Elevated vibration on tail pulley. Possible misalignment.", recommendation: "Check pulley alignment and belt tracking.", timestamp: "2026-08-27T08:00:00Z" },
  { id: "ANL-003", beltId: "BLT-007", category: "vibration", component: "Gearbox - Stage 2", value: 14.2, unit: "mm/s", threshold: 10, status: "critical", severity: "critical", details: "Gear mesh frequency anomaly.齿轮点蚀 suspected.", recommendation: "Stop gearbox and inspect gear teeth. Plan replacement.", timestamp: "2026-08-27T07:30:00Z" },
  { id: "ANL-004", beltId: "BLT-001", category: "vibration", component: "Idler Station 5", value: 3.2, unit: "mm/s", threshold: 10, status: "normal", severity: "low", details: "Vibration within normal range.", recommendation: "Continue monitoring.", timestamp: "2026-08-27T08:00:00Z" },
  // Temperature
  { id: "ANL-005", beltId: "BLT-002", category: "temperature", component: "Bearing Housing", value: 71.8, unit: "°C", threshold: 65, status: "critical", severity: "high", details: "Temperature 6.8°C above critical threshold. Thermal imaging shows hotspot.", recommendation: "Lubricate bearing immediately. Check cooling system.", timestamp: "2026-08-27T08:00:00Z" },
  { id: "ANL-006", beltId: "BLT-003", category: "temperature", component: "Joint Area", value: 78.4, unit: "°C", threshold: 65, status: "critical", severity: "critical", details: "Extreme overheating at joint section. Risk of belt delamination.", recommendation: "Emergency shutdown. Inspect joint integrity.", timestamp: "2026-08-27T08:00:00Z" },
  { id: "ANL-007", beltId: "BLT-007", category: "temperature", component: "Crusher Discharge", value: 58.7, unit: "°C", threshold: 55, status: "warning", severity: "medium", details: "Temperature above warning threshold. Friction buildup detected.", recommendation: "Check belt tension and idler rotation.", timestamp: "2026-08-27T08:00:00Z" },
  { id: "ANL-008", beltId: "BLT-004", category: "temperature", component: "Drive Station", value: 38.9, unit: "°C", threshold: 55, status: "normal", severity: "low", details: "Temperature normal.", recommendation: "Continue monitoring.", timestamp: "2026-08-27T08:00:00Z" },
  // Motor Current
  { id: "ANL-009", beltId: "BLT-003", category: "motor_current", component: "Main Drive Motor", value: 285, unit: "A", threshold: 250, status: "critical", severity: "high", details: "Motor current 14% above rated. Mechanical resistance increasing.", recommendation: "Check belt loading and idler friction. Reduce feed rate.", timestamp: "2026-08-27T08:00:00Z" },
  { id: "ANL-010", beltId: "BLT-002", category: "motor_current", component: "Crusher Feed Motor", value: 218, unit: "A", threshold: 250, status: "warning", severity: "medium", details: "Current trending upward. 87% of rated capacity.", recommendation: "Monitor trend. Schedule belt inspection.", timestamp: "2026-08-27T08:00:00Z" },
  { id: "ANL-011", beltId: "BLT-001", category: "motor_current", component: "Haulage Motor", value: 180, unit: "A", threshold: 250, status: "normal", severity: "low", details: "Motor operating at 72% rated current. Normal.", recommendation: "Continue monitoring.", timestamp: "2026-08-27T08:00:00Z" },
  // Acoustic
  { id: "ANL-012", beltId: "BLT-003", category: "acoustic", component: "Splice Point 4", value: 82, unit: "dB", threshold: 75, status: "critical", severity: "high", details: "Abnormal harmonic pattern detected. Metal-on-metal sound signature.", recommendation: "Inspect splice joint immediately. Possible delamination.", timestamp: "2026-08-27T07:45:00Z" },
  { id: "ANL-013", beltId: "BLT-007", category: "acoustic", component: "Transfer Point B", value: 71, unit: "dB", threshold: 75, status: "warning", severity: "medium", details: "Elevated noise level. Scraping sound detected.", recommendation: "Check belt edge alignment and scraper condition.", timestamp: "2026-08-27T08:00:00Z" },
  { id: "ANL-014", beltId: "BLT-001", category: "acoustic", component: "Drive Station", value: 58, unit: "dB", threshold: 75, status: "normal", severity: "low", details: "Normal acoustic profile.", recommendation: "Continue monitoring.", timestamp: "2026-08-27T08:00:00Z" },
  // Load/Tension
  { id: "ANL-015", beltId: "BLT-003", category: "load_tension", component: "Belt Span 12", value: 112, unit: "kN", threshold: 100, status: "critical", severity: "high", details: "Tension 12% above safe limit. Abnormal belt stress.", recommendation: "Adjust take-up tension. Check for belt slip.", timestamp: "2026-08-27T08:00:00Z" },
  { id: "ANL-016", beltId: "BLT-002", category: "load_tension", component: "Belt Span 7", value: 95, unit: "kN", threshold: 100, status: "warning", severity: "medium", details: "Tension at 95% threshold. Belt sag detected.", recommendation: "Monitor tension trend. Schedule idler inspection.", timestamp: "2026-08-27T08:00:00Z" },
  { id: "ANL-017", beltId: "BLT-004", category: "load_tension", component: "Belt Span 1", value: 76, unit: "kN", threshold: 100, status: "normal", severity: "low", details: "Tension within normal range.", recommendation: "Continue monitoring.", timestamp: "2026-08-27T08:00:00Z" },
  // Electromagnetic
  { id: "ANL-018", beltId: "BLT-003", category: "electromagnetic", component: "Belt Section C", value: 0.82, unit: "signal", threshold: 0.5, status: "critical", severity: "critical", details: "Steel cord damage detected. Electromagnetic signature shows 3 broken cords.", recommendation: "Emergency belt replacement. Splice integrity compromised.", timestamp: "2026-08-27T07:00:00Z" },
  { id: "ANL-019", beltId: "BLT-001", category: "electromagnetic", component: "Belt Span 3", value: 0.35, unit: "signal", threshold: 0.5, status: "normal", severity: "low", details: "Steel cord integrity normal.", recommendation: "Continue monitoring.", timestamp: "2026-08-27T08:00:00Z" },
  // Camera/AI Vision
  { id: "ANL-020", beltId: "BLT-003", category: "camera_ai", component: "Joint Section 12", value: 94.2, unit: "%", threshold: 80, status: "critical", severity: "critical", details: "YOLO-STOD detected joint rupture. Surface crack width: 3.2mm.", recommendation: "Immediate belt section replacement. Stop conveyor.", timestamp: "2026-08-27T08:15:00Z" },
  { id: "ANL-021", beltId: "BLT-002", category: "camera_ai", component: "Belt Span 7", value: 88.7, unit: "%", threshold: 80, status: "critical", severity: "high", details: "Tear detected at 180m mark. Length: 15cm. Width: 2.1mm.", recommendation: "Schedule emergency repair. Apply temporary splice.", timestamp: "2026-08-27T06:42:00Z" },
  { id: "ANL-022", beltId: "BLT-007", category: "camera_ai", component: "Loading Zone", value: 76.5, unit: "%", threshold: 80, status: "warning", severity: "medium", details: "Surface abrasion detected. Area: 200cm². Depth: 1.2mm.", recommendation: "Monitor progression. Schedule repair during next shutdown.", timestamp: "2026-08-26T14:20:00Z" },
  { id: "ANL-023", beltId: "BLT-001", category: "camera_ai", component: "Return Side Idler 5", value: 82.1, unit: "%", threshold: 80, status: "warning", severity: "low", details: "Edge damage detected. 5cm from belt edge.", recommendation: "Check belt tracking. Adjust idler alignment.", timestamp: "2026-08-26T09:10:00Z" },
];

export const thermalTrendData = [
  { time: "00:00", drive: 35, bearing: 40, joint: 42 },
  { time: "02:00", drive: 36, bearing: 42, joint: 45 },
  { time: "04:00", drive: 38, bearing: 48, joint: 52 },
  { time: "06:00", drive: 40, bearing: 55, joint: 60 },
  { time: "08:00", drive: 42, bearing: 62, joint: 68 },
  { time: "10:00", drive: 44, bearing: 72, joint: 78 },
  { time: "12:00", drive: 45, bearing: 68, joint: 75 },
  { time: "14:00", drive: 43, bearing: 65, joint: 70 },
  { time: "16:00", drive: 41, bearing: 60, joint: 65 },
  { time: "18:00", drive: 39, bearing: 55, joint: 58 },
  { time: "20:00", drive: 37, bearing: 48, joint: 50 },
  { time: "22:00", drive: 36, bearing: 43, joint: 45 },
];
